# Generated by Django 6.0.3 on 2026-03-16 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="allow_network",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="script_file",
            field=models.FileField(blank=True, null=True, upload_to="job_scripts/"),
        ),
        migrations.AddField(
            model_name="job",
            name="timeout_seconds",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobrun",
            name="started_at",
            field=models.DateTimeField(),
        ),
    ]
