# Generated by Django 6.0.3 on 2026-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_allow_network_job_script_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrun",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
