# Generated by Django 6.0.3 on 2026-03-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_jobrun_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="script_file",
        ),
        migrations.AddField(
            model_name="job",
            name="command",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.CharField(default="python:3.11-slim", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="schedule",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="JobFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="job_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
    ]
