# Generated by Django 6.0.3 on 2026-03-19 01:02

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_remove_job_script_file_job_command_job_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobfile",
            name="file",
            field=models.FileField(upload_to=jobs.models.job_file_upload_path),
        ),
        migrations.AlterField(
            model_name="jobrun",
            name="log_file",
            field=models.FileField(
                blank=True, null=True, upload_to=jobs.models.job_run_log_upload_path
            ),
        ),
    ]
