# Generated by Django 6.0.3 on 2026-04-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_jobfile_file_alter_jobrun_log_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="email_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
