# Generated by Django 6.0.3 on 2026-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobrun_email_error_jobrun_email_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="api_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
