# Generated by Django 6.0.3 on 2026-04-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_jobrun_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="custom_email_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="state_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="updated_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="JobState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
    ]
