# Generated by Django 6.0.3 on 2026-04-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_jobrun_custom_email_content_jobrun_state_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="notification_preference",
            field=models.CharField(
                choices=[
                    ("ALL", "All jobs runs"),
                    ("CUSTOM", "Only on custom notifications requested in job"),
                    ("NONE", "No notifications"),
                ],
                default="ALL",
                max_length=20,
            ),
        ),
    ]
