# Generated by Django 6.0.3 on 2026-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_notification_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="notification_preference",
            field=models.CharField(
                choices=[
                    ("ALL", "All job runs"),
                    ("CUSTOM", "Only for custom notifications requested in job"),
                    ("NONE", "No notifications"),
                ],
                default="ALL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobrun",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("NOT REQUESTED", "Not Requested"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
