name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~

            if [ ! -d "job-automation-platform" ]; then
              echo "Cloning repo..."
              git clone https://jakeymac:${{ secrets.GH_TOKEN }}@github.com/jakeymac/job-automation-platform.git job-automation-platform
            fi

            cd ~/job-automation-platform

            echo "Pulling latest version of the repo..."
            git pull https://jakeymac:${{ secrets.GH_TOKEN }}@github.com/jakeymac/job-automation-platform.git

            cat <<EOF > .env
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            DEBUG=False

            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

            DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}
            REDIS_URL=redis://redis:6379/0
            EOF

            echo "Pulling latest images..."
            echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u jakeymac --password-stdin

            docker compose pull

            echo "Restarting containers..."
            docker compose up -d --remove-orphans

            echo "Cleaning unused images..."
            docker image prune -f

            echo "Deployment complete!"