name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~

            if [ ! -d "job-automation-platform" ]; then
              echo "Cloning repo..."
              git clone https://jakeymac:${{ secrets.GH_TOKEN }}@github.com/jakeymac/job-automation-platform.git job-automation-platform
            fi

            cd ~/job-automation-platform

            echo "Pulling latest version of the repo..."
            git pull https://jakeymac:${{ secrets.GH_TOKEN }}@github.com/jakeymac/job-automation-platform.git

            echo "Pulling latest images..."
            echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u jakeymac --password-stdin

            docker compose pull

            echo "Restarting containers..."
            docker compose down
            docker compose up -d --remove-orphans

            echo "Cleaning unused images..."
            docker image prune -f

            echo "Deployment complete!"